# Generated by Django 4.2.23 on 2025-08-31 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppraisalProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createuser',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppraisalProject.department'),
            preserve_default=False,
        ),
    ]
