# Generated by Django 4.2.23 on 2025-08-27 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppraisalProject', '0002_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='hod',
        ),
    ]
