# Generated by Django 4.2.23 on 2025-08-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppraisalProject', '0003_remove_department_hod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityName', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='departmentName',
        ),
    ]
