# Generated by Django 4.2.23 on 2025-08-27 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppraisalProject', '0004_activities_rename_name_department_departmentname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=120)),
                ('month', models.CharField(max_length=40)),
                ('activity_name', models.CharField(max_length=120)),
                ('detail', models.JSONField(default=dict)),
                ('merged_proof', models.FileField(blank=True, upload_to='proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
