# Generated by Django 4.2.23 on 2025-09-01 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppraisalProject', '0004_alter_createuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysubmission',
            name='activity_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppraisalProject.activities'),
        ),
    ]
