# Generated by Django 4.2.23 on 2025-08-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppraisalProject', '0005_activitysubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysubmission',
            name='detail',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
