# Generated by Django 4.2.23 on 2025-09-01 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppraisalProject', '0005_alter_activitysubmission_activity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='createuser',
            name='reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL),
        ),
    ]
